import type { Benefit } from './types'

export const CITIZEN_COUNT = 6034

export const BENEFITS: Benefit[] = [
  {
    id: 'parksookeun',
    title: '양구군립 박수근미술관',
    category: '관광지',
    image: '/assets/benefits/parksookeun.jpg',
    link: 'http://www.parksookeun.or.kr/',
    location: '강원특별자치도 양구군 양구읍 박수근로 265-15',
    item: '관람료',
    discount: '기존 6,000원 → 사이버군민 3,000원',
    howto: '현장에서 사이버군민증, 신분증 제시 후 결제',
  },
  {
    id: 'astro',
    title: '국토정중앙천문대',
    category: '관광지',
    image: '/assets/benefits/astro.jpg',
    link: 'https://www.ygtour.kr/Home/H20000/H20200/placeDetail?place_no=8',
    location: '강원특별자치도 양구군 국토정중앙면 국토정중앙로 127',
    item: '입장료',
    discount: '기존 6,000원 → 사이버군민 3,000원',
    howto: '현장에서 사이버군민증, 신분증 제시 후 결제',
  },
  {
    id: 'arboretum',
    title: '양구수목원',
    category: '관광지',
    image: '/assets/benefits/arboretum.jpg',
    link: 'https://www.yg-eco.kr/',
    location: '강원특별자치도 양구군 동면 숨골로310번길 131',
    item: '수목원 입장료',
    discount: '기존 6,000원 → 사이버군민 3,000원',
    howto: '현장에서 사이버군민증, 신분증 제시 후 결제',
  },
  {
    id: 'dutayeon',
    title: '두타연',
    category: '관광지',
    image: '/assets/benefits/dutayeon.jpg',
    link: 'https://stour.ticketplay.zone/portal/F50000/F50100/html',
    location: '강원 양구군 방산면 두타연로 297',
    item: '두타연 입장료',
    discount: '기존 6,000원 → 사이버군민 3,000원',
    howto:
      '홈페이지에서 사전예약(선결제/방문결제) 후, 현장에서 사이버군민증·신분증을 제시해 주세요. 선결제한 경우 현장에서 차액을 환불합니다.',
  },
  {
    id: 'baekkop',
    title: '배꼽제빵소',
    category: '카페',
    image: '/assets/benefits/baekkop.jpg',
    link: 'https://map.naver.com/p/entry/place/1411055525',
    location: '강원 양구군 양구읍 박수근로365번길 20-2',
    item: '전 품목',
    discount: '10% 할인',
    howto: '현장에서 사이버군민증, 신분증 제시 후 결제',
  },
  {
    id: 'terrace',
    title: '카페 테라스82',
    category: '카페',
    image: '/assets/benefits/terrace.jpg',
    link: 'https://map.naver.com/p/entry/place/1492229621',
    location: '강원특별자치 양구군 동면 약수터길 82',
    item: '카페 전 메뉴',
    discount: '10% 할인',
    howto: '현장에서 사이버군민증 및 신분증 제시',
  },
  {
    id: 'punches',
    title: '카페 펀치스 11-2',
    category: '카페',
    image: '/assets/benefits/punches.jpg',
    link: 'https://www.instagram.com/fun_cheers',
    location: '강원특별자치도 양구군 해안면 땅굴로 11-2',
    item: '카페 전 메뉴, 건시래기',
    discount: '10% 할인',
    howto: '현장에서 사이버군민증 및 신분증 제시',
  },
  {
    id: 'yangguga',
    title: '양구"佳" 가',
    category: '체험',
    image: '/assets/benefits/yangguga.jpg',
    link: 'https://map.naver.com/p/search/강원특별자치도%20양구군%20양구읍%20소양웅진길%2093-17',
    location: '강원특별자치도 양구군 양구읍 소양웅진길93-17',
    item: '체험프로그램',
    discount: '10% 할인',
    howto: '1) 전화로 사전 예약 2) 현장에서 사이버군민증, 신분증 제시 후 결제',
    phone: '010-2386-1407',
  },
  {
    id: 'farm',
    title: '박수근마을 체험농원',
    category: '체험',
    image: '/assets/benefits/farm.jpg',
    link: 'https://map.naver.com/p/entry/place/1744377020',
    location: '강원특별자치도 양구군 양구읍 박수근로 252-9 1층 하얀집',
    item: '상품, 체험프로그램',
    discount: '10% 할인',
    howto:
      '1) 전화로 사전 예약 2) 현장에서 사이버군민증 제시 후 결제 또는 환급(예약자). 개인 1인 체험은 불가하며, 가족 단위부터 체험 가능합니다.',
    phone: '0507-1437-6602',
  },
  {
    id: 'wood',
    title: '수근아트프로젝트(목공체험)',
    category: '체험',
    image: '/assets/benefits/wood.jpg',
    link: '',
    location: '강원특별자치도 양구군 양구읍 파로호로 937-30',
    item: '목공 체험 프로그램',
    discount: '10% 할인',
    howto: '1) 전화로 사전 예약 2) 현장에서 사이버군민증, 신분증 제시 후 결제',
    phone: '010-6416-5619',
  },
  {
    id: 'mokhwa',
    title: '목화 모텔',
    category: '숙박',
    image: '/assets/benefits/mokhwa.jpg',
    link: 'https://map.naver.com/p/entry/place/15037814',
    location: '양구군 양구읍 비봉로 40-43',
    item: '평일 주말 숙박비',
    discount: '10% 할인',
    howto: '1) 전화로 사전 문의 2) 결제금액 선입금 3) 예약완료',
  },
  {
    id: 'dumu',
    title: '두무산촌마을',
    category: '숙박',
    image: '/assets/benefits/dumu.jpg',
    link: 'http://www.ygfarmtour.com/bbs/content.php?co_id=1_7_1',
    location: '양구군 국토정중앙면 관대두무로 1058-5',
    item: '평일, 주말 숙박비',
    discount: '1박에 1만원 할인',
    howto: '1) 전화로 사전 문의 2) 결제금액 선입금 3) 예약완료',
  },
  {
    id: 'yangjimal',
    title: '양지말펜션 / 양지말2펜션',
    category: '숙박',
    image: '/assets/benefits/yangjimal.jpg',
    link: 'http://www.xn--pz2bu1lvudo8evyo.kr/',
    location: '양구군 양구읍 박수근로421번길 8',
    item: '연박 숙박비',
    discount: '연박 시 평일 1만원 할인',
    howto: '1) 전화로 사전 문의 2) 결제금액 선입금 3) 예약완료',
  },
  {
    id: 'mansu',
    title: '만수장여관',
    category: '숙박',
    image: '/assets/benefits/mansu.jpg',
    link: 'https://map.naver.com/p/search/양구군%20방산면%20장거리길%2014-3',
    location: '양구군 방산면 장거리길 14-3',
    item: '평일 주말 숙박비',
    discount: '5천원 할인',
    howto: '1) 전화로 사전 문의 2) 결제금액 선입금 3) 예약완료',
  },
  {
    id: 'forest',
    title: '포레스트벨리',
    category: '숙박',
    image: '/assets/benefits/forest.jpg',
    link: 'https://www.instagram.com/forestvalley_pension/',
    location: '양구군 방산면 성곡로 1562-8',
    item: '연박 숙박비',
    discount: '연박 시 둘째 날부터 30% 할인',
    howto: '1) 전화로 사전 문의 2) 결제금액 선입금 3) 예약완료',
  },
  {
    id: 'jige',
    title: '지게마을농촌체험마을',
    category: '숙박',
    image: '/assets/benefits/jige.jpg',
    link: 'http://palrang.co.kr/main/index.html',
    location: '양구군 동면 팔랑리 1185-1',
    item: '평일 주말 숙박비',
    discount: '1인당 3천원 할인',
    howto:
      '1) 전화로 사전 예약 2) 사이버 군민증 모바일 캡처본을 해당 번호로 전송 3) 결제 금액 선입금 4) 예약 완료',
  },
  {
    id: 'neutinamu',
    title: '느티나무펜션',
    category: '숙박',
    image: '/assets/benefits/neutinamu.jpg',
    link: 'https://m.blog.naver.com/PostList.naver?blogId=gml7225',
    location: '양구군 양구읍 박수근로365번길 42-3',
    item: '평일 숙박비',
    discount: '2만원 할인',
    howto: '1) 전화로 사전 문의 2) 결제금액 선입금 3) 예약완료',
  },
  {
    id: 'hanna',
    title: '한나펜션',
    category: '숙박',
    image: '/assets/benefits/hanna.jpg',
    link: 'http://ygpension.com/',
    location: '양구군 양구읍 박수근로213번길 31-29',
    item: '주말 숙박비',
    discount: '10% 할인',
    howto: '1) 전화로 사전 문의 2) 결제금액 선입금 3) 예약완료',
  },
  {
    id: 'ungjin',
    title: '웅진계곡숲야영장',
    category: '숙박',
    image: '/assets/benefits/ungjin.jpg',
    link: 'https://map.naver.com/p/search/웅진계곡숲야영장',
    location: '양구군 양구읍 소양웅진길 35-6',
    item: '평일 숙박비',
    discount: '20% 할인',
    howto: '1) 전화로 사전 문의 2) 결제금액 선입금 3) 예약완료. 동절기는 운영 안내를 먼저 확인해 주세요.',
  },
  {
    id: 'tteurak',
    title: '뜨락펜션',
    category: '숙박',
    image: '/assets/benefits/tteurak.jpg',
    link: 'https://blog.naver.com/jsngmmi',
    location: '양구군 양구읍 박수근로 365번길 20-18',
    item: '평일 주말 숙박비',
    discount: '10% 할인',
    howto: '1) 전화로 사전 문의 2) 결제금액 선입금 3) 예약완료',
  },
  {
    id: 'salon',
    title: '학미용실',
    category: '기타',
    image: null,
    link: 'https://map.naver.com/p/entry/place/1891396401',
    location: '강원특별자치도 양구군 양구읍 해시계로 23-10',
    item: '전 품목',
    discount: '5% 할인',
    howto: '현장에서 사이버군민증, 신분증 제시 후 결제',
  },
  {
    id: 'hangwa',
    title: '양구전통한과',
    category: '기타',
    image: '/assets/benefits/hangwa.jpg',
    link: 'https://yghangwa.com/page/index?tpl=etc%2FYG_Cyber.html',
    location: '강원특별자치도 양구군 양구읍 박수근로85번길 20',
    item: '전품목',
    discount: '10% 할인',
    howto:
      '현장 구매: 사이버군민증과 신분증을 제시한 뒤 결제 / 인터넷 구매: 홈페이지 링크를 통해서만 구입 가능',
  },
]

export const CATEGORIES = ['전체', '관광지', '카페', '체험', '숙박', '기타'] as const

export const CARD_DESIGNS = [
  { id: 1 as const, name: '배꼽이', color: '#c9a0ff' },
  { id: 2 as const, name: '새싹이', color: '#c8e86a' },
  { id: 3 as const, name: '곰실이', color: '#f3b6a0' },
  { id: 4 as const, name: '꽥꽥이', color: '#f6d44a' },
]

export const FAQS = [
  {
    q: '양구사랑 사이버 군민증은 무엇인가요?',
    a: '국내·외 누구나 주민등록을 옮기지 않고도 사이버 양구군민이 되어, 관광지 할인·제휴 업체 혜택·양구 소식 알림을 받을 수 있는 제도입니다.',
  },
  {
    q: '누가 발급받을 수 있나요?',
    a: '관외 주민등록자를 대상으로 합니다. 양구에 주민등록이 있는 분은 기존 군민 혜택을 이용하시면 됩니다.',
  },
  {
    q: '현장에서 어떻게 사용하나요?',
    a: '모바일 화면 또는 인쇄한 군민증 이미지와 함께, 신분증(주민등록증·운전면허증·여권)을 반드시 제시해야 합니다. 군민증만으로는 할인이 적용되지 않습니다.',
  },
  {
    q: '관광지 입장료는 얼마인가요?',
    a: '박수근미술관, 국토정중앙천문대, 양구수목원, 두타연은 기존 6,000원에서 사이버군민 3,000원으로 적용됩니다. 두타연은 사전예약이 필요합니다.',
  },
  {
    q: '숙박 할인은 왜 전화 예약인가요?',
    a: '대부분의 숙박 제휴점은 전화 문의 후 선입금으로 예약을 확정합니다. 방문 전에 할인 적용 여부와 빈방을 꼭 확인해 주세요.',
  },
  {
    q: '유효기간이 있나요?',
    a: '발급일로부터 3년입니다. 만료 전에 다시 발급받으면 계속해서 혜택을 이용할 수 있습니다.',
  },
]
